[package]
name = "traverse"
version = "0.1.0"
authors = ["Marcel Baur <mail@marcelbaur.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
